version: '2'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - MYSQL_ADMIN_PASS=admin
    command:
      - ./supporting_files/run.sh
